contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #bamregionextractor channel"
    url: https://nfcore.slack.com/channels/bamregionextractor
    about: Discussion about the nf-core/bamregionextractor pipeline
